### ISSUE TITLE
AA-Button disappears when RCSBuildAid is installed

### ISSUE THREAD

**Issue by fat-lobyte** [Boris-Barboris/AtmosphereAutopilot#1]
Hi!
For some strange reason, the AA-Button is not present, if the RCSBuildAid plugin is installed

http://forum.kerbalspaceprogram.com/threads/35996-1-0-2-RCS-Build-Aid-v0-7-2
https://github.com/m4v/RCSBuildAid

Removing RCSBuildAid makes the AA-Button appear again.
I could produce this in a clean install, so interaction with a 3rd mod can be excluded.

Update: The offending file is apparently RCSBuildAid/Plugins/RCSBuildAidToolbar.dll
This is the source coude of the file: https://github.com/m4v/RCSBuildAid/blob/master/RCSBuildAidToolbar/Toolbar.cs

**Comment by Boris-Barboris** [comment]
direct consequence of https://github.com/m4v/RCSBuildAid/issues/23
Install http://forum.kerbalspaceprogram.com/threads/60863 to avoid.
Added exception handling in plugin initialization, https://github.com/Boris-Barboris/AtmosphereAutopilot/commit/94e7043c18fc1fc6a7b03fc64e1ec23e00e380a5 to adress such issues. Is included in 1.0 release .zip file.
