### ISSUE TITLE
Neo-GUI not working in 1.8

### ISSUE THREAD

**Issue by radistmorse** [Boris-Barboris/AtmosphereAutopilot#21]
The way assetBundles are working changed somewhere around unity 2017, and now the "old way" became deprecated. This patch  changes things on the loading front.

Also, building the assetBundle is now a real pain, since importing something dependent on UnityEngine.UI in the unity editor is broken in 2019.2.2 which KSP uses. You need to manually put the UnityEngine.UI.dll into the "plugins" folder, open the project, then import the AA.UI.dll, then import the prefab, then remove the UnityEngine.UI.dll, because importing it breaks other stuff, then pray to some unity gods or something... So I decided to just add the already exported bundle as a binary. Hopefully it will last another several years.
[diff.txt](https://github.com/Boris-Barboris/AtmosphereAutopilot/files/3828651/diff.txt)
I didn't do it as a pull request because I'm lazy :)

**Comment by Boris-Barboris** [comment]
3ba2aa339c51aa0b7db29844d6af6b17d53e1dfe
