### ISSUE TITLE
NullReferenceExceptions

### ISSUE THREAD

**Issue by TedThompson** [Boris-Barboris/AtmosphereAutopilot#22]
```
[EXC 11:53:01.074] NullReferenceException: Object reference not set to an instance of an object
	VesselAutopilot.SetAutopilotTarget (System.Boolean initialize) (at <9d71e4043e394d78a6cf9193ad011698>:0)
	VesselAutopilot.SetAutopilot (System.Boolean initialize) (at <9d71e4043e394d78a6cf9193ad011698>:0)
	VesselAutopilot.Update () (at <9d71e4043e394d78a6cf9193ad011698>:0)
	Vessel.Update () (at <9d71e4043e394d78a6cf9193ad011698>:0)
```
Here's the entire log.

[KSP.log](https://github.com/Boris-Barboris/AtmosphereAutopilot/files/3882050/KSP.log)

**Comment by Boris-Barboris** [comment]
AA's code is not in the trace and I see no direct connection between VesselAutopilot.SetAutopilotTarget and it either. Are you adamant that after AA removal this problem disappears and reappears again the moment AA is installed?

**Comment by TedThompson** [comment]
I didn't do any such tests, I found the exceptions when I was looking at the log for other reasons. 

Are you saying its not your mod? If so, sorry to trouble you.

**Comment by Boris-Barboris** [comment]
> Are you saying its not your mod? If so, sorry to trouble you.

Yes, this is stock code that is crashing. Some mod could have done something to cause this, but I don't think it's AA.
