### ISSUE TITLE
Different PID value for different side

### ISSUE THREAD

**Issue by Kerbinator-Fras** [Boris-Barboris/AtmosphereAutopilot#25]
When flying at extreme conditions, the control authority for pitching up and pitching down is becoming very different.
When I fly my stock-aero Eve SSTO with stock propeller engines at 10km+ at eve, since ***pitch-stability tend to roll your craft to AoA=0 but at 16km you need very high AoA - and you need pitch-stability or fuel tank's angular lift will ruin everything***, AA will **pitch down a lot** (10m/s delta-vertical-vel) when you input a down control , but **pitch up a little** (1m/s delta-vertical-vel) when you input a up control (standard FBW). This is the most severe when you are climbing with barely acceleratable power (counting the thrust of props, only -200L/D, plus L=G means that Acc=G/200, and prop already set to max since I bind prop torque with main throttle) and near-stalling (10deg AoA) at 16.9km of Eve. Increasing the final altitude and velocity is very important for making Eve SSTO to orbit.
![screenshot264](https://user-images.githubusercontent.com/55748582/100253133-b5a67500-2f7b-11eb-9581-e496a3032693.png)
~~Btw, I still want to thank you for making this amazing mod, with the help of AA I can easily climb to 16km without consuming EC (solar bay, with SAS I can only climb to 14.5km before consuming EC), and climb to 140m/s@16900m, with SAS I got best 138m/s@16250m, same craft. (This craft is capable for Eve Orbit@90km with 1 Kerbal+Seat, 20 airlocks, and 150m/s nuclear dv, 1500m/s ion dv that is already enough for making it home.~~

**Comment by Kerbinator-Fras** [comment]
PS: when I intend to pitch this stuff down for decreasing 1m/s vertical vel up (about pitching down 0.5 deg), AA often pitch it down for 20-30deg. If you hit S hard and trying to stop the pitchdown, it will still pitch down about 10deg when stable. With G/200, such little excess thrust, this really make you lose a lot of speed.

**Comment by Boris-Barboris** [comment]
For your particular case i suggest toggling precision mode (caps lock usually) or/and decreasing pitch rate limit (craft settings) to something like 0.3.

Sensitivity is supposed to be different when close to max AoA, you just need to reduce the max pitch ang vel so your pitch down is less agressive.

PS: there are no PIDs here.
