### ISSUE TITLE
KSP-AVC -> Version file contains errors

### ISSUE THREAD

**Issue by RealKolago** [Boris-Barboris/AtmosphereAutopilot#3]
I see an error in the log:
KSP-AVC -> Version file contains errors: https://raw.githubusercontent.com/Boris-Barboris/AtmosphereAutopilot/master/AtmosphereAutopilot/AtmosphereAutopilot.version

**Comment by Boris-Barboris** [comment]
As I've commented [here](http://forum.kerbalspaceprogram.com/index.php?/topic/72169-11-ksp-avc-add-on-version-checker-plugin-1161-miniavc-ksp-avc-online-2016-04-19/&page=11#comment-2493737), I have no idea what's wrong. Syntax is intact, FAR uses the [same format](https://github.com/ferram4/Ferram-Aerospace-Research/blob/2ef8b0a54d7dec1957046602c3c35951e13bd61e/GameData/FerramAerospaceResearch/FAR.version)

And AVC actually is correctly parsing the same local file. If someone has a solution, feel free to point me to it.

**Comment by Boris-Barboris** [comment]
fixed in https://github.com/Boris-Barboris/AtmosphereAutopilot/commit/66c11fdb8dfd6c62b9bda7f490b45663555a327a
