### ISSUE TITLE
Allow save to config to disable angle snap of rotation (default 3deg and not editable in configs)

### ISSUE THREAD

**Issue by Kerbinator-Fras** [Boris-Barboris/AtmosphereAutopilot#32]
this is for 0.001deg-level inclination control of SSTO to prepare for precise equitorial orbit around Kerbin (as KSC is not precisely on the equator, 2' south for runway). If it's in somewhere I didn't find in config, you may tell me and I'll appreciate it. 
description: craft settings-roll ang vel controller, every time I have to manually set it to 0 before takeoff. reverting to launch, exit and restart KSP, etc. will cause this value to return to 3deg, making me have to set it to 0 every time before takeoff (shrugging.png here)

**Comment by Boris-Barboris** [comment]
[VesselSerializable("wing_leveler")]
[GlobalSerializable("wing_leveler")]
[AutoGuiAttr("Wing leveler", true)]
public bool wing_leveler = true;

This is a name of a toggle/button for roll-snapping, just press it once and it should persist.
