### ISSUE TITLE
Cant set waypoint on cruise flight

### ISSUE THREAD

**Issue by hexahigh** [Boris-Barboris/AtmosphereAutopilot#33]
When i try to set a waypoint using cruise flight and press on "Select waypoint" "map: pick" and select a planet using the map i get a popup saying "missed"

![image](https://user-images.githubusercontent.com/97455552/176385977-cf760f07-d7b8-472a-b364-a14bd6cd2eee.png)

**Comment by Boris-Barboris** [comment]
Hi! You're supposed to click on the surface of your current planet, so you'll need to zoom in as close as you can.

**Comment by hexahigh** [comment]
Does it work with other rockets?

**Comment by hexahigh** [comment]
Im pressing the planets surface and it still says missed

**Comment by Boris-Barboris** [comment]
I don't understand you.
No, it doesn't work with rockets, only planes.
I can't reproduce it on my KSP install.
