### ISSUE TITLE
Locally built code doesn't run

### ISSUE THREAD

**Issue by krisalyssa** [Boris-Barboris/AtmosphereAutopilot#8]
First, an introduction: I have more than 25 years experience in software development, but it's been about 18 years since I've done anything remotely related to Windows development (including C# and Mono). It's entirely possible that there's something I'm not doing that's immediately obvious to someone else.

Since I'm running on Mac OS X, I have installed Xamarin Studio 6.1.1 build 15, Mono 4.6.1, and GTK+ 2.24.23.

I forked the source code repository and cloned it locally. I opened the solution file, set the active configuration to Debug, cleaned, and built the solution (the level above the `AtmosphereAutopilot`, `AtmosphereAutopilot.GUI`, and `TestingConsole` projects). Four errors in `TestingConsole`, but the other two projects appear to have built okay [1]. I copied the files in `bin/Debug` to `GameData/AtmosphereAutopilot`, overwriting what was already there.

When I launch KSP with the code built locally, I get this in `KSP.log`:

```
[ERR 19:46:11.924] AssemblyLoader: Exception loading 'AtmosphereAutopilot': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0
  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0

Additional information about this exception:

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.FlightModel' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.DirectorController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.AngularAccAdaptiveController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.AngularVelAdaptiveController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.PitchYawAngularVelocityController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.PitchAngularVelocityController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.RollAngularVelocityController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.YawAngularVelocityController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.MouseDirector' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.CruiseController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.ProgradeThrustController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.AoAController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.SideslipController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.PitchAoAController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.StandardFlyByWire' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.TopModuleManager' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.TopModuleManager+CraftSettingsWindow' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'PartMass' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'EngineMoment' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.AngularAccAdaptiveController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.PitchYawAngularAccController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.PitchYawAngularAccController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'AtmosphereAutopilot.AngularAccAdaptiveController' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'CenterIndicator' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'CruiseMode' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'HeightMode' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'SettingsProfile' from assembly 'AtmosphereAutopilot, Version=1.5.7.0, Culture=neutral, PublicKeyToken=null'.
```

To make sure this isn't a debug-versus-release thing, I changed the configuration to Release, cleaned, built again [2], and copied the resulting files to `GameData/AtmosphereAutopilot`. Same results.

Since we appear to be running completely different systems to develop, I'm not going to ask you to diagnose _my_ system. (If you already know why it's not working for me, I wouldn't turn down that answer, however. 😄 ) What _would_ help is if you could describe or document how _you_ build the code. Hopefully that will show me if I'm missing some essential step or steps.

I'm happy to document/edit the build instructions in a new section in `README.md` once this is working.

[1] The first time I built `AtmosphereAutopilot`, I got an error because the `.csproj` file has a hardcoded reference to the `COPY` command, which Mac OS X doesn't have. Until I figure out how to copy `README.md` in a cross-platform-safe fashion, I've commented it out of the `.csproj` file. I don't think this should cause my built code to fail.

[2] The first time I built with the Release configuration, I got an error because the output paths in the `.csproj` file are hardcoded to refer to an installation under Steam, which isn't valid for me (I have the full app from Squad). I edited the `.csproj` file so the output paths are `bin/Release` instead. Since my results were the same as when I built with the Debug configuration, I don't think this is the cause of my local code failing either.

**Comment by Boris-Barboris** [comment]
Are you sure you're trying it on KSP 1.2 pre-release? Because master branch will not work on previous versions. You might wanna clone older commits for 1.1.3 code.

Also, release zip from [here](http://forum.kerbalspaceprogram.com/index.php?/topic/124417-113-atmosphereautopilot-157/&do=findComment&comment=2771416) is a good example of what you need in the gamedata folder 1.2pre version. If you are not touching NeoGUI prefab itself, you should be fine with only those steps you performed, but make sure you copy atmosphereautopilotprefabs from the zip to AA folder in gamedata.

**Comment by krisalyssa** [comment]
Ah -- I'm building against 1.1.3 code. I'll pull a 1.2-pre release and try building against that.

**Comment by krisalyssa** [comment]
Works with the 1.2-pre code!
